namespace QRCode.Abstracts;

public abstract class AbstractQRCode
{
    protected QRCodeData QrCodeData { get; }

    protected AbstractQRCode(QRCodeData data)
    {
        QrCodeData = data;
    }

    /// <summary>
    /// Set a QRCodeData object that will be used to generate QR code. Used in COM Objects connections
    /// </summary>
    /// <param name="data">Need a QRCodeData object generated by QRCodeGenerator.CreateQrCode()</param>
    public void Dispose()
    {
        QrCodeData.Dispose();
    }
}